spawn_robot:
  ros__parameters:
    robot_name: "atlas" # name of the robot, certain topic names are namespaced with this name
    sdf_file: "COSTAR_HUSKY_SENSOR_CONFIG_REDUCED/model.sdf" # path to the sdf file in the share folder of the package
    world: "rubicon" # name of the world in which the robot should be spawned
    use_imu: true
    # start pose of the robot (atlas) in the world -7.0 0.0 3.96 0.0 0.0 0.0
    x: "-7.0"
    y: "0.0"
    z: "3.96"
    roll: "0.0"
    pitch: "0.0"
    yaw: "0.0"
    
teleop_joy:
  ros__parameters:
    enable_teleop_joy: true
    joy_config: "xbox" # "xbox" or "ps3"
    joy_dev: "0" # joystick device
    cmd_vel_topic: "cmd_vel" # topic to publish the cmd_vel to
    joy_topic: "joy" # topic to subscribe to for the joystick input
